- name: Descubrir paquete nginx
  command: "amazon-linux-extras enable nginx1"
  become: true

- name: Instalar nginx
  command: "amazon-linux-extras install nginx1 -y"
  become: true

- name: Configurar archivo de Nginx
  template:
    src: "nginx.config.j2"
    dest: "/etc/nginx/conf.d/default.conf"
  become: true

- name: Iniciar servicio de Nginx
  ansible.builtin.service:
    name: "nginx"
    state: started
  become: true
